[package]
name = "dsptch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12"
bytes = "1"
druid = "0.7"
midir = "0.7"
parking_lot = "0.11"
pipewire = "0.4"
